<?php
$z[0]=Array("arcurl","",82,97);
$z[1]=Array("title","",109,149);
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("litpic","",156,171);
$z[3]=Array("arcurl","",298,313);
$z[4]=Array("title","",315,329);
$z[5]=Array("pubdate","",339,386);
$z[5][4]['function']="MyDate('Y-m-d',@me)";
$z[6]=Array("description","",436,511);
$z[6][4]['function']="cn_substr(@me,50)";
$z[7]=Array("arcurl","",523,538);

?>