<div class="pointlist2">
                            <div class="ptpic"><a href="[field:arcurl/]"><img alt="[field:title function='html2text(@me)'/]" src="[field:litpic/]" /></a></div>
                            <div class="ptright">
                                <div class="pttit"><a href="[field:arcurl/]">[field:title/]</a><span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span></div>
                                <p>[field:description function='html2text(@me)' function='cn_substr(@me,50)'/]...<a href="[field:arcurl/]" class="desc1">ฯ๊ว้</a></p>
                            </div>
                        </div>