
  <m:item name='织梦模板' link='http://dedecms.codesdq.com/' rank='' target='_blank' />
  <m:item name='源码大全' link='http://www.codesdq.com/' rank='' target='_blank' />
  <m:item name='源码大全论坛' link='http://bbs.codesdq.com/' rank='' target='_blank' />
  <m:item name='西部数码代理' link='http://www.whxin.net/' rank='' target='_blank' />
  <m:item name='电脑知识大全' link='http://diannaodiy.net/' rank='' target='_blank' /
