<?php
$z[0]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n            ",219,380);
$z[0][4]['typeid']="3";
$z[1]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n            ",535,696);
$z[1][4]['typeid']="3";
$z[2]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n            ",851,1012);
$z[2][4]['typeid']="3";

?>