<?php
$z[0]=Array("arclist","\r\n                        <li >\r\n        	                <a target=\"_blank\" class=\"a1\" href=\"[field:arcurl/]\" ><img alt=\"[field:title function='html2text(@me)'/]\"  src=\"[field:litpic/]\"/></a>\r\n                            <p><a target=\"_blank\" href=\"[field:arcurl/]\" >[field:title/]</a></p>\r\n                        </li>\r\n                    ",5459,5898);
$z[0][4]['row']="4";
$z[0][4]['orderby']="pubdate";
$z[0][4]['type']="image.";
$z[0][4]['imgwidth']="224";
$z[0][4]['imgheight']="170";
$z[1]=Array("arclist","\r\n                        <li >\r\n        	                <a target=\"_blank\" class=\"a1\" href=\"[field:arcurl/]\" ><img alt=\"[field:title function='html2text(@me)'/]\"  src=\"[field:litpic/]\"/></a>\r\n                            <p><a target=\"_blank\" href=\"[field:arcurl/]\" >[field:title/]</a></p>\r\n                        </li>\r\n                    ",6170,6609);
$z[1][4]['row']="4";
$z[1][4]['orderby']="pubdate";
$z[1][4]['type']="image.";
$z[1][4]['imgwidth']="224";
$z[1][4]['imgheight']="170";

?>