<?php
$z[0]=Array("channel","\r\n            <li> <a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n            ",277,425);
$z[0][4]['type']="top";
$z[0][4]['row']="7";
$z[1]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n            ",560,721);
$z[1][4]['typeid']="1";
$z[2]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n            ",810,971);
$z[2][4]['typeid']="2";
$z[3]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n            ",1059,1220);
$z[3][4]['typeid']="3";
$z[4]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n            ",1309,1470);
$z[4][4]['typeid']="4";
$z[5]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n            ",1559,1720);
$z[5][4]['typeid']="5";
$z[6]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n            ",1809,1970);
$z[6][4]['typeid']="6";
$z[7]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n            ",2059,2220);
$z[7][4]['typeid']="7";

?>